### ISSUE TITLE
Limit the number of parallelism

### ISSUE THREAD

**Issue by uncttao** [OpenCilk/opencilk-project#71]
Hi, how can I limit the Cilk runtime scheduler to a maximum N number of threads (instead of all available threads)? I need this for benchmark and other purposes. Thanks!

**Comment by neboat** [comment]
You can use the `CILK_NWORKERS` environment variable to set the number of Cilk workers the program uses at runtime.  For example, to run the classic Cilk fib(40) on 1 worker:
```
$ CILK_NWORKERS=1 ./fib 40
```
Equivalently:
```
$ export CILK_NWORKERS=1
$ ./fib 40
```
Let me know if that works for you.

**Comment by uncttao** [comment]
This works. Thank you!

**Comment by vivkumar** [comment]
Can we change the worker count dynamically during the program execution?

**Comment by neboat** [comment]
Currently, no.  We don't offer an API function to change the number of workers during program execution.  Such a function turns out to be dangerous outside of a few specific contexts, and as a result, we have been reluctant to add that functionality without understanding how people want to use it.

What would you want to do with that functionality, @vivkumar?

**Comment by vivkumar** [comment]
We wanted to use OpenCilk for evaluating https://ftp.cs.wisc.edu/sohi/papers/2014/PLDI_2014_Adaptive.pdf
